# Generated by Django 5.2.1 on 2025-05-29 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentchunk',
            old_name='emebdding_id',
            new_name='embedding_id',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user'], name='document_do_user_id_57c4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document'], name='document_do_documen_c5ea3f_idx'),
        ),
    ]
